### ISSUE TITLE
Add a height listener

### ISSUE THREAD

**Issue by EenDev** [TrollyLoki/Movecraft#6]
I think it would add a lot to the plugin if you could go pass a y-limit height, and then travel to a world defined in the config. 

I would add this myself, but as a new plugin programmer, movecraft code blows my mind... I don't understand it.

**Comment by eirikh1996** [comment]
That can also be done in a separate plugin as well. I don't think there is need to bloat Movecraft with that stuff you are suggesting

**Comment by TrollyLoki** [comment]
I agree, because this feature is so case specific, it should be implemented by an external plugin. I may create an example plugin for this.

**Comment by TrollyLoki** [comment]
I agree, because this feature is so case specific, it should be implemented by an external plugin. I may create an example plugin for this.
